export const WORDS_HIRAGANA = [
  // --- Original List ---
  { kana: 'あめ', romaji: 'ame', meaning: 'rain / candy' },
  { kana: 'いぬ', romaji: 'inu', meaning: 'dog' },
  { kana: 'うみ', romaji: 'umi', meaning: 'sea' },
  { kana: 'えき', romaji: 'eki', meaning: 'station' },
  { kana: 'おかね', romaji: 'okane', meaning: 'money' },
  { kana: 'かさ', romaji: 'kasa', meaning: 'umbrella' },
  { kana: 'きって', romaji: 'kitte', meaning: 'stamp' },
  { kana: 'くつ', romaji: 'kutsu', meaning: 'shoes' },
  { kana: 'けむり', romaji: 'kemuri', meaning: 'smoke' },
  { kana: 'こえ', romaji: 'koe', meaning: 'voice' },
  { kana: 'さかな', romaji: 'sakana', meaning: 'fish' },
  { kana: 'しお', romaji: 'shio', meaning: 'salt' },
  { kana: 'すし', romaji: 'sushi', meaning: 'sushi' },
  { kana: 'せかい', romaji: 'sekai', meaning: 'world' },
  { kana: 'そら', romaji: 'sora', meaning: 'sky' },
  { kana: 'たまご', romaji: 'tamago', meaning: 'egg' },
  { kana: 'ちかてつ', romaji: 'chikatetsu', meaning: 'subway' },
  { kana: 'つき', romaji: 'tsuki', meaning: 'moon' },
  { kana: 'てがみ', romaji: 'tegami', meaning: 'letter' },
  { kana: 'とり', romaji: 'tori', meaning: 'bird' },
  { kana: 'なまえ', romaji: 'namae', meaning: 'name' },
  { kana: 'にわ', romaji: 'niwa', meaning: 'garden' },
  { kana: 'ぬの', romaji: 'nuno', meaning: 'cloth' },
  { kana: 'ねこ', romaji: 'neko', meaning: 'cat' },
  { kana: 'のみもの', romaji: 'nomimono', meaning: 'drink' },
  { kana: 'はな', romaji: 'hana', meaning: 'flower' },
  { kana: 'ひと', romaji: 'hito', meaning: 'person' },
  { kana: 'ふゆ', romaji: 'fuyu', meaning: 'winter' },
  { kana: 'へや', romaji: 'heya', meaning: 'room' },
  { kana: 'ほし', romaji: 'hoshi', meaning: 'star' },
  { kana: 'まど', romaji: 'mado', meaning: 'window' },
  { kana: 'みず', romaji: 'mizu', meaning: 'water' },
  { kana: 'むし', romaji: 'mushi', meaning: 'insect' },
  { kana: 'め', romaji: 'me', meaning: 'eye' },
  { kana: 'もり', romaji: 'mori', meaning: 'forest' },
  { kana: 'やま', romaji: 'yama', meaning: 'mountain' },
  { kana: 'ゆき', romaji: 'yuki', meaning: 'snow' },
  { kana: 'よる', romaji: 'yoru', meaning: 'night' },
  { kana: 'らじお', romaji: 'rajio', meaning: 'radio' },
  { kana: 'りんご', romaji: 'ringo', meaning: 'apple' },
  { kana: 'るすばん', romaji: 'rusuban', meaning: 'house-sitting' },
  { kana: 'れきし', romaji: 'rekishi', meaning: 'history' },
  { kana: 'ろうか', romaji: 'rouka', meaning: 'hallway' },
  { kana: 'わたし', romaji: 'watashi', meaning: 'I / me' },
  { kana: 'をとこ', romaji: 'otoko', meaning: 'man' },
  { kana: 'じしょ', romaji: 'jisho', meaning: 'dictionary' },
  { kana: 'でんしゃ', romaji: 'densha', meaning: 'train' },
  { kana: 'びょういん', romaji: 'byouin', meaning: 'hospital', youon: true },
  { kana: 'ぎんこう', romaji: 'ginkou', meaning: 'bank' },
  { kana: 'ざっし', romaji: 'zasshi', meaning: 'magazine' },
  { kana: 'きゃく', romaji: 'kyaku', meaning: 'guest / customer', youon: true },
  { kana: 'きゅうり', romaji: 'kyuuri', meaning: 'cucumber', youon: true },
  { kana: 'きょうと', romaji: 'kyouto', meaning: 'Kyoto', youon: true },
  { kana: 'しゃしん', romaji: 'shashin', meaning: 'photograph', youon: true },
  { kana: 'しゅじん', romaji: 'shujin', meaning: 'husband / master', youon: true },
  { kana: 'しょくじ', romaji: 'shokuji', meaning: 'meal', youon: true },
  { kana: 'ちゃわん', romaji: 'chawan', meaning: 'rice bowl', youon: true },
  { kana: 'ちゅうもん', romaji: 'chuumon', meaning: 'order (food)', youon: true },
  { kana: 'ちょうちょ', romaji: 'choucho', meaning: 'butterfly', youon: true },
  { kana: 'にゅうがく', romaji: 'nyuugaku', meaning: 'school enrollment', youon: true },
  { kana: 'ひゃく', romaji: 'hyaku', meaning: 'hundred', youon: true },
  { kana: 'みゃく', romaji: 'myaku', meaning: 'pulse', youon: true },
  { kana: 'りょこう', romaji: 'ryokou', meaning: 'travel', youon: true },
  { kana: 'りゅうがく', romaji: 'ryuugaku', meaning: 'studying abroad', youon: true },
  { kana: 'ぎゃく', romaji: 'gyaku', meaning: 'reverse / opposite', youon: true },
  { kana: 'じゅぎょう', romaji: 'jugyou', meaning: 'lesson / class', youon: true },
  { kana: 'じょうず', romaji: 'jouzu', meaning: 'skillful', youon: true },
  { kana: 'びょうき', romaji: 'byouki', meaning: 'illness', youon: true },
  { kana: 'ぴゅーぴゅー', romaji: 'pyuupyuu', meaning: 'whistling wind', youon: true },
  { kana: 'みょうじ', romaji: 'myouji', meaning: 'family name', youon: true },

  // --- 300 New Hiragana Words ---
  { kana: 'あさ', romaji: 'asa', meaning: 'morning' },
  { kana: 'あした', romaji: 'ashita', meaning: 'tomorrow' },
  { kana: 'きのう', romaji: 'kinou', meaning: 'yesterday' },
  { kana: 'あき', romaji: 'aki', meaning: 'autumn' },
  { kana: 'はる', romaji: 'haru', meaning: 'spring' },
  { kana: 'なつ', romaji: 'natsu', meaning: 'summer' },
  { kana: 'いえ', romaji: 'ie', meaning: 'house' },
  { kana: 'かぎ', romaji: 'kagi', meaning: 'key' },
  { kana: 'とけい', romaji: 'tokei', meaning: 'clock' },
  { kana: 'かばん', romaji: 'kaban', meaning: 'bag' },
  { kana: 'いす', romaji: 'isu', meaning: 'chair' },
  { kana: 'つくえ', romaji: 'tsukue', meaning: 'desk' },
  { kana: 'はし', romaji: 'hashi', meaning: 'chopsticks' },
  { kana: 'さら', romaji: 'sara', meaning: 'plate' },
  { kana: 'おちゃ', romaji: 'ocha', meaning: 'tea', youon: true },
  { kana: 'ごはん', romaji: 'gohan', meaning: 'meal / rice' },
  { kana: 'おかし', romaji: 'okashi', meaning: 'sweets' },
  { kana: 'きょうしつ', romaji: 'kyoushitsu', meaning: 'classroom', youon: true },
  { kana: 'せんせい', romaji: 'sensei', meaning: 'teacher' },
  { kana: 'がくせい', romaji: 'gakusei', meaning: 'student' },
  { kana: 'ともだち', romaji: 'tomodachi', meaning: 'friend' },
  { kana: 'かぞく', romaji: 'kazoku', meaning: 'family' },
  { kana: 'おとうさん', romaji: 'otousan', meaning: 'father' },
  { kana: 'おかあさん', romaji: 'okaasan', meaning: 'mother' },
  { kana: 'おにいさん', romaji: 'oniisan', meaning: 'older brother' },
  { kana: 'おねえさん', romaji: 'oneesan', meaning: 'older sister' },
  { kana: 'おとうと', romaji: 'otouto', meaning: 'younger brother' },
  { kana: 'いもうと', romaji: 'imouto', meaning: 'younger sister' },
  { kana: 'あかちゃん', romaji: 'akachan', meaning: 'baby', youon: true },
  { kana: 'あたま', romaji: 'atama', meaning: 'head' },
  { kana: 'かお', romaji: 'kao', meaning: 'face' },
  { kana: 'みみ', romaji: 'mimi', meaning: 'ear' },
  { kana: 'くち', romaji: 'kuchi', meaning: 'mouth' },
  { kana: 'て', romaji: 'te', meaning: 'hand' },
  { kana: 'あし', romaji: 'ashi', meaning: 'foot / leg' },
  { kana: 'ゆび', romaji: 'yubi', meaning: 'finger' },
  { kana: 'はな', romaji: 'hana', meaning: 'nose' },
  { kana: 'おなか', romaji: 'onaka', meaning: 'stomach' },
  { kana: 'いたい', romaji: 'itai', meaning: 'painful' },
  { kana: 'あつい', romaji: 'atsui', meaning: 'hot' },
  { kana: 'さむい', romaji: 'samui', meaning: 'cold (weather)' },
  { kana: 'つめたい', romaji: 'tsumetai', meaning: 'cold (touch)' },
  { kana: 'はやい', romaji: 'hayai', meaning: 'fast / early' },
  { kana: 'おそい', romaji: 'osoi', meaning: 'slow / late' },
  { kana: 'おもい', romaji: 'omoi', meaning: 'heavy' },
  { kana: 'かるい', romaji: 'karui', meaning: 'light' },
  { kana: 'たかい', romaji: 'takai', meaning: 'expensive / tall' },
  { kana: 'やすい', romaji: 'yasui', meaning: 'cheap' },
  { kana: 'ひろい', romaji: 'hiroi', meaning: 'wide' },
  { kana: 'せまい', romaji: 'semai', meaning: 'narrow' },
  { kana: 'たのしい', romaji: 'tanoshii', meaning: 'fun' },
  { kana: 'おいしい', romaji: 'oishii', meaning: 'delicious' },
  { kana: 'むずかしい', romaji: 'muzukashii', meaning: 'difficult' },
  { kana: 'やさしい', romaji: 'yasashii', meaning: 'easy / kind' },
  { kana: 'たべる', romaji: 'taberu', meaning: 'to eat' },
  { kana: 'のむ', romaji: 'nomu', meaning: 'to drink' },
  { kana: 'いく', romaji: 'iku', meaning: 'to go' },
  { kana: 'くる', romaji: 'kuru', meaning: 'to come' },
  { kana: 'みる', romaji: 'miru', meaning: 'to see' },
  { kana: 'きく', romaji: 'kiku', meaning: 'to listen / hear' },
  { kana: 'かく', romaji: 'kaku', meaning: 'to write' },
  { kana: 'よむ', romaji: 'yomu', meaning: 'to read' },
  { kana: 'ねる', romaji: 'neru', meaning: 'to sleep' },
  { kana: 'おきる', romaji: 'okiru', meaning: 'to wake up' },
  { kana: 'かう', romaji: 'kau', meaning: 'to buy' },
  { kana: 'あう', romaji: 'au', meaning: 'to meet' },
  { kana: 'あそぶ', romaji: 'asobu', meaning: 'to play' },
  { kana: 'まつ', romaji: 'matsu', meaning: 'to wait' },
  { kana: 'はなす', romaji: 'hanasu', meaning: 'to talk' },
  { kana: 'あるく', romaji: 'aruku', meaning: 'to walk' },
  { kana: 'はしる', romaji: 'hashiru', meaning: 'to run' },
  { kana: 'およぐ', romaji: 'oyogu', meaning: 'to swim' },
  { kana: 'かえる', romaji: 'kaeru', meaning: 'to return' },
  { kana: 'つくる', romaji: 'tsukuru', meaning: 'to make' },
  { kana: 'つかう', romaji: 'tsukau', meaning: 'to use' },
  { kana: 'しる', romaji: 'shiru', meaning: 'to know' },
  { kana: 'わかる', romaji: 'wakaru', meaning: 'to understand' },
  { kana: 'おしえる', romaji: 'oshieru', meaning: 'to teach' },
  { kana: 'わすれる', romaji: 'wasureru', meaning: 'to forget' },
  { kana: 'はじめる', romaji: 'hajimeru', meaning: 'to begin' },
  { kana: 'おわる', romaji: 'owaru', meaning: 'to end' },
  { kana: 'がんばる', romaji: 'ganbaru', meaning: 'to do one’s best' },
  { kana: 'わらう', romaji: 'warau', meaning: 'to laugh' },
  { kana: 'うたう', romaji: 'utau', meaning: 'to sing' },
  { kana: 'おどる', romaji: 'odoru', meaning: 'to dance' },
  { kana: 'ひま', romaji: 'hima', meaning: 'free time' },
  { kana: 'いそがしい', romaji: 'isogashii', meaning: 'busy' },
  { kana: 'あぶない', romaji: 'abunai', meaning: 'dangerous' },
  { kana: 'へん', romaji: 'hen', meaning: 'strange' },
  { kana: 'じゆう', romaji: 'jiyuu', meaning: 'freedom', youon: true },
  { kana: 'しあわせ', romaji: 'shiawase', meaning: 'happiness' },
  { kana: 'かなしい', romaji: 'kanashii', meaning: 'sad' },
  { kana: 'こわい', romaji: 'kowai', meaning: 'scary' },
  { kana: 'ねむい', romaji: 'nemui', meaning: 'sleepy' },
  { kana: 'きいろ', romaji: 'kiiro', meaning: 'yellow' },
  { kana: 'あか', romaji: 'aka', meaning: 'red' },
  { kana: 'あお', romaji: 'ao', meaning: 'blue' },
  { kana: 'しろ', romaji: 'shiro', meaning: 'white' },
  { kana: 'くろ', romaji: 'kuro', meaning: 'black' },
  { kana: 'みどり', romaji: 'midori', meaning: 'green' },
  { kana: 'むらさき', romaji: 'murasaki', meaning: 'purple' },
  { kana: 'ちゃいろ', romaji: 'chairo', meaning: 'brown' },
  { kana: 'くも', romaji: 'kumo', meaning: 'cloud' },
  { kana: 'かぜ', romaji: 'kaze', meaning: 'wind' },
  { kana: 'かみなり', romaji: 'kaminari', meaning: 'thunder' },
  { kana: 'ひかり', romaji: 'hikari', meaning: 'light' },
  { kana: 'かげ', romaji: 'kage', meaning: 'shadow' },
  { kana: 'みち', romaji: 'michi', meaning: 'road' },
  { kana: 'はし', romaji: 'hashi', meaning: 'bridge' },
  { kana: 'こうえん', romaji: 'kouen', meaning: 'park' },
  { kana: 'おみせ', romaji: 'omise', meaning: 'shop' },
  { kana: 'かいしゃ', romaji: 'kaisha', meaning: 'company', youon: true },
  { kana: 'しごと', romaji: 'shigoto', meaning: 'work' },
  { kana: 'じかん', romaji: 'jikan', meaning: 'time' },
  { kana: 'きょう', romaji: 'kyou', meaning: 'today', youon: true },
  { kana: 'こんや', romaji: 'konya', meaning: 'tonight', youon: true },
  { kana: 'さき', romaji: 'saki', meaning: 'ahead' },
  { kana: 'あと', romaji: 'ato', meaning: 'after' },
  { kana: 'となり', romaji: 'tonari', meaning: 'next to' },
  { kana: 'なか', romaji: 'naka', meaning: 'inside' },
  { kana: 'そと', romaji: 'soto', meaning: 'outside' },
  { kana: 'うえ', romaji: 'ue', meaning: 'up / above' },
  { kana: 'した', romaji: 'shita', meaning: 'down / below' },
  { kana: 'まえ', romaji: 'mae', meaning: 'front / before' },
  { kana: 'うしろ', romaji: 'ushiro', meaning: 'behind' },
  { kana: 'ひだり', romaji: 'hidari', meaning: 'left' },
  { kana: 'みぎ', romaji: 'migi', meaning: 'right' },
  { kana: 'ここ', romaji: 'koko', meaning: 'here' },
  { kana: 'そこ', romaji: 'soko', meaning: 'there' },
  { kana: 'あそこ', romaji: 'asoko', meaning: 'over there' },
  { kana: 'どこ', romaji: 'doko', meaning: 'where' },
  { kana: 'だれ', romaji: 'dare', meaning: 'who' },
  { kana: 'なに', romaji: 'nani', meaning: 'what' },
  { kana: 'いつ', romaji: 'itsu', meaning: 'when' },
  { kana: 'どうして', romaji: 'doushite', meaning: 'why' },
  { kana: 'たくさん', romaji: 'takusan', meaning: 'many / a lot' },
  { kana: 'すこし', romaji: 'sukoshi', meaning: 'a little' },
  { kana: 'ぜんぶ', romaji: 'zenbu', meaning: 'everything' },
  { kana: 'はんぶん', romaji: 'hanbun', meaning: 'half' },
  { kana: 'いち', romaji: 'ichi', meaning: 'one' },
  { kana: 'に', romaji: 'ni', meaning: 'two' },
  { kana: 'さん', romaji: 'san', meaning: 'three' },
  { kana: 'し', romaji: 'shi', meaning: 'four' },
  { kana: 'ご', romaji: 'go', meaning: 'five' },
  { kana: 'ろく', romaji: 'roku', meaning: 'six' },
  { kana: 'しち', romaji: 'shichi', meaning: 'seven' },
  { kana: 'はち', romaji: 'hachi', meaning: 'eight' },
  { kana: 'く', romaji: 'ku', meaning: 'nine' },
  { kana: 'じゅう', romaji: 'juu', meaning: 'ten', youon: true },
  { kana: 'ひゃく', romaji: 'hyaku', meaning: 'hundred', youon: true },
  { kana: 'せん', romaji: 'sen', meaning: 'thousand' },
  { kana: 'まん', romaji: 'man', meaning: 'ten thousand' },
  { kana: 'えん', romaji: 'en', meaning: 'yen' },
  { kana: 'ひとつ', romaji: 'hitotsu', meaning: 'one thing' },
  { kana: 'ふたつ', romaji: 'futatsu', meaning: 'two things' },
  { kana: 'みっつ', romaji: 'mittsu', meaning: 'three things' },
  { kana: 'よっつ', romaji: 'yottsu', meaning: 'four things' },
  { kana: 'いつつ', romaji: 'itsutsu', meaning: 'five things' },
  { kana: 'むっつ', romaji: 'muttsu', meaning: 'six things' },
  { kana: 'ななつ', romaji: 'nanatsu', meaning: 'seven things' },
  { kana: 'やっつ', romaji: 'yattsu', meaning: 'eight things' },
  { kana: 'ここのつ', romaji: 'kokonotsu', meaning: 'nine things' },
  { kana: 'とお', romaji: 'too', meaning: 'ten things' },
  { kana: 'ひとり', romaji: 'hitori', meaning: 'one person' },
  { kana: 'ふたり', romaji: 'futari', meaning: 'two people' },
  { kana: 'こども', romaji: 'kodomo', meaning: 'child' },
  { kana: 'おとな', romaji: 'otona', meaning: 'adult' },
  { kana: 'じしょ', romaji: 'jisho', meaning: 'dictionary' },
  { kana: 'ほん', romaji: 'hon', meaning: 'book' },
  { kana: 'ノート', romaji: 'nooto', meaning: 'notebook' },
  { kana: 'えんぴつ', romaji: 'enpitsu', meaning: 'pencil' },
  { kana: 'かみ', romaji: 'kami', meaning: 'paper' },
  { kana: 'ぶんしょう', romaji: 'bunshou', meaning: 'sentence', youon: true },
  { kana: 'いみ', romaji: 'imi', meaning: 'meaning' },
  { kana: 'こたえ', romaji: 'kotae', meaning: 'answer' },
  { kana: 'しつもん', romaji: 'shitsumon', meaning: 'question' },
  { kana: 'べんきょう', romaji: 'benkyou', meaning: 'study', youon: true },
  { kana: 'れんしゅう', romaji: 'renshuu', meaning: 'practice', youon: true },
  { kana: 'しけん', romaji: 'shiken', meaning: 'exam' },
  { kana: 'せいかい', romaji: 'seikai', meaning: 'correct' },
  { kana: 'まちがい', romaji: 'machigai', meaning: 'mistake' },
  { kana: 'じゅんび', romaji: 'junbi', meaning: 'preparation' },
  { kana: 'てつだい', romaji: 'tetsudai', meaning: 'help' },
  { kana: 'おくりもの', romaji: 'okurimono', meaning: 'gift' },
  { kana: 'おいわい', romaji: 'oiwai', meaning: 'celebration' },
  { kana: 'おみやげ', romaji: 'omiyage', meaning: 'souvenir' },
  { kana: 'まつり', romaji: 'matsuri', meaning: 'festival' },
  { kana: 'じんじゃ', romaji: 'jinja', meaning: 'shrine', youon: true },
  { kana: 'おてら', romaji: 'otera', meaning: 'temple' },
  { kana: 'きょうかい', romaji: 'kyoukai', meaning: 'church' },
  { kana: 'おっと', romaji: 'otto', meaning: 'husband' },
  { kana: 'つま', romaji: 'tsuma', meaning: 'wife' },
  { kana: 'かのじょ', romaji: 'kanojo', meaning: 'she / girlfriend', youon: true },
  { kana: 'かれ', romaji: 'kare', meaning: 'he / boyfriend' },
  { kana: 'こいびと', romaji: 'koibito', meaning: 'lover' },
  { kana: 'けっこん', romaji: 'kekkon', meaning: 'marriage' },
  { kana: 'やくそく', romaji: 'yakusoku', meaning: 'promise' },
  { kana: 'うそ', romaji: 'uso', meaning: 'lie' },
  { kana: 'ゆめ', romaji: 'yume', meaning: 'dream' },
  { kana: 'ひみつ', romaji: 'himitsu', meaning: 'secret' },
  { kana: 'ちから', romaji: 'chikara', meaning: 'power' },
  { kana: 'こころ', romaji: 'kokoro', meaning: 'heart' },
  { kana: 'きもち', romaji: 'kimochi', meaning: 'feeling' },
  { kana: 'あんしん', romaji: 'anshin', meaning: 'relief' },
  { kana: 'しんぱい', romaji: 'shinpai', meaning: 'worry' },
  { kana: 'ざんねん', romaji: 'zannen', meaning: 'disappointing' },
  { kana: 'むり', romaji: 'muri', meaning: 'impossible' },
  { kana: 'だいじょうぶ', romaji: 'daijoubu', meaning: 'okay' },
  { kana: 'ひつよう', romaji: 'hitsuyou', meaning: 'necessary', youon: true },
  { kana: 'だいじ', romaji: 'daiji', meaning: 'important' },
  { kana: 'しずか', romaji: 'shizuka', meaning: 'quiet' },
  { kana: 'にぎやか', romaji: 'nigiyaka', meaning: 'lively' },
  { kana: 'べんり', romaji: 'benri', meaning: 'convenient' },
  { kana: 'ふべん', romaji: 'fuben', meaning: 'inconvenient' },
  { kana: 'ゆうめい', romaji: 'yuumei', meaning: 'famous' },
  { kana: 'しんせつ', romaji: 'shinsetsu', meaning: 'kind' },
  { kana: 'ひま', romaji: 'hima', meaning: 'free (time)' },
  { kana: 'わかい', romaji: 'wakai', meaning: 'young' },
  { kana: 'ふるい', romaji: 'furui', meaning: 'old' },
  { kana: 'あたらしい', romaji: 'atarashii', meaning: 'new' },
  { kana: 'ながい', romaji: 'nagai', meaning: 'long' },
  { kana: 'みじかい', romaji: 'mijikai', meaning: 'short' },
  { kana: 'つよい', romaji: 'tsuyoi', meaning: 'strong' },
  { kana: 'よわい', romaji: 'yowai', meaning: 'weak' },
  { kana: 'くらい', romaji: 'kurai', meaning: 'dark' },
  { kana: 'あかるい', romaji: 'akarui', meaning: 'bright' },
  { kana: 'きい', romaji: 'kii', meaning: 'yellow' },
  { kana: 'きいろ', romaji: 'kiiro', meaning: 'yellow' },
  { kana: 'すてき', romaji: 'suteki', meaning: 'lovely' },
  { kana: 'きれい', romaji: 'kirei', meaning: 'beautiful / clean' },
  { kana: 'よごれた', romaji: 'yogoreta', meaning: 'dirty' },
  { kana: 'まるい', romaji: 'marui', meaning: 'round' },
  { kana: 'しかくい', romaji: 'shikakui', meaning: 'square' },
  { kana: 'あまい', romaji: 'amai', meaning: 'sweet' },
  { kana: 'からい', romaji: 'karai', meaning: 'spicy' },
  { kana: 'すっぱい', romaji: 'suppai', meaning: 'sour' },
  { kana: 'にがい', romaji: 'nigai', meaning: 'bitter' },
  { kana: 'しおからい', romaji: 'shiokarai', meaning: 'salty' },
  { kana: 'こい', romaji: 'koi', meaning: 'thick / dark color' },
  { kana: 'うすい', romaji: 'usui', meaning: 'thin / light color' },
  { kana: 'ひだり', romaji: 'hidari', meaning: 'left' },
  { kana: 'みぎ', romaji: 'migi', meaning: 'right' },
  { kana: 'うで', romaji: 'ude', meaning: 'arm' },
  { kana: 'かた', romaji: 'kata', meaning: 'shoulder' },
  { kana: 'むね', romaji: 'mune', meaning: 'chest' },
  { kana: 'こし', romaji: 'koshi', meaning: 'waist / hip' },
  { kana: 'ひざ', romaji: 'hiza', meaning: 'knee' },
  { kana: 'け', romaji: 'ke', meaning: 'hair / fur' },
  { kana: 'こえ', romaji: 'koe', meaning: 'voice' },
  { kana: 'かぜ', romaji: 'kaze', meaning: 'cold (illness)' },
  { kana: 'ねつ', romaji: 'netsu', meaning: 'fever' },
  { kana: 'せき', romaji: 'seki', meaning: 'cough' },
  { kana: 'くすり', romaji: 'kusuri', meaning: 'medicine' },
  { kana: 'けんこう', romaji: 'kenkou', meaning: 'health' },
  { kana: 'たいえん', romaji: 'taien', meaning: 'discharge from hospital' },
  { kana: 'さんぽ', romaji: 'sanpo', meaning: 'walk / stroll' },
  { kana: 'うんどう', romaji: 'undou', meaning: 'exercise' },
  { kana: 'すいえい', romaji: 'suiei', meaning: 'swimming' },
  { kana: 'じゅうどう', romaji: 'juudou', meaning: 'judo', youon: true },
  { kana: 'あいきどう', romaji: 'aikidou', meaning: 'aikido' },
  { kana: 'からて', romaji: 'karate', meaning: 'karate' },
  { kana: 'にんじゃ', romaji: 'ninja', meaning: 'ninja', youon: true },
  { kana: 'さむらい', romaji: 'samurai', meaning: 'samurai' },
  { kana: 'はいく', romaji: 'haiku', meaning: 'haiku' },
  { kana: 'いけばな', romaji: 'ikebana', meaning: 'flower arrangement' },
  { kana: 'さどう', romaji: 'sadou', meaning: 'tea ceremony' },
  { kana: 'おめん', romaji: 'omen', meaning: 'mask' },
  { kana: 'ゆかた', romaji: 'yukata', meaning: 'yukata' },
  { kana: 'きもの', romaji: 'kimono', meaning: 'kimono' },
  { kana: 'げた', romaji: 'geta', meaning: 'geta (sandals)' },
  { kana: 'うちわ', romaji: 'uchiwa', meaning: 'fan' },
  { kana: 'せんす', romaji: 'sensu', meaning: 'folding fan' },
  { kana: 'たたみ', romaji: 'tatami', meaning: 'tatami mat' },
  { kana: 'ふとん', romaji: 'futon', meaning: 'futon' },
  { kana: 'こたつ', romaji: 'kotatsu', meaning: 'heated table' },
  { kana: 'おふろ', romaji: 'ofuro', meaning: 'bath' },
  { kana: 'せっけん', romaji: 'sekken', meaning: 'soap' },
  { kana: 'たおる', romaji: 'taoru', meaning: 'tonel' },
  { kana: 'せんたく', romaji: 'sentaku', meaning: 'laundry' },
  { kana: 'そうじ', romaji: 'souji', meaning: 'cleaning' },
  { kana: 'りょうり', romaji: 'ryouri', meaning: 'cooking', youon: true },
  { kana: 'かいもの', romaji: 'kaimono', meaning: 'shopping' },
  { kana: 'にわ', romaji: 'niwa', meaning: 'garden' },
  { kana: 'はな', romaji: 'hana', meaning: 'flower' },
  { kana: 'き', romaji: 'ki', meaning: 'tree' },
  { kana: 'は', romaji: 'ha', meaning: 'leaf' },
  { kana: 'ね', romaji: 'ne', meaning: 'root' },
  { kana: 'たね', romaji: 'tane', meaning: 'seed' },
  { kana: 'にわとり', romaji: 'niwatori', meaning: 'chicken' },
  { kana: 'うし', romaji: 'ushi', meaning: 'cow' },
  { kana: 'うま', romaji: 'uma', meaning: 'horse' },
  { kana: 'ぶた', romaji: 'buta', meaning: 'pig' },
  { kana: 'ひつじ', romaji: 'hitsuji', meaning: 'sheep' },
  { kana: 'さる', romaji: 'saru', meaning: 'monkey' },
  { kana: 'くま', romaji: 'kuma', meaning: 'bear' },
  { kana: 'とら', romaji: 'tora', meaning: 'tiger' },
  { kana: 'らいおん', romaji: 'raion', meaning: 'lion' },
  { kana: 'ぞう', romaji: 'zou', meaning: 'elephant' },
  { kana: 'きりん', romaji: 'kirin', meaning: 'giraffe' },
  { kana: 'へび', romaji: 'hebi', meaning: 'snake' },
  { kana: 'かめ', romaji: 'kame', meaning: 'turtle' },
  { kana: 'かえる', romaji: 'kaeru', meaning: 'frog' },
  { kana: 'さかな', romaji: 'sakana', meaning: 'fish' },
  { kana: 'いか', romaji: 'ika', meaning: 'squid' },
  { kana: 'たこ', romaji: 'tako', meaning: 'octopus' },
  { kana: 'えび', romaji: 'ebi', meaning: 'shrimp' },
  { kana: 'かに', romaji: 'kani', meaning: 'crab' },
  { kana: 'かい', romaji: 'kai', meaning: 'shellfish' },
  { kana: 'むし', romaji: 'mushi', meaning: 'insect' },
  { kana: 'ちょう', romaji: 'chou', meaning: 'butterfly', youon: true },
  { kana: 'あり', romaji: 'ari', meaning: 'ant' },
  { kana: 'はち', romaji: 'hachi', meaning: 'bee' },
  { kana: 'くも', romaji: 'kumo', meaning: 'spider' },
  { kana: 'か', romaji: 'ka', meaning: 'mosquito' },
  { kana: 'はえ', romaji: 'hae', meaning: 'fly' },
  { kana: 'ごきぶり', romaji: 'gokiburi', meaning: 'cockroach' },
  { kana: 'ねずみ', romaji: 'nezumi', meaning: 'mouse' },
  { kana: 'うさぎ', romaji: 'usagi', meaning: 'rabbit' },
  { kana: 'きつね', romaji: 'kitsune', meaning: 'fox' },
  { kana: 'たぬき', romaji: 'tanuki', meaning: 'raccoon dog' },
  { kana: 'しか', romaji: 'shika', meaning: 'deer' },
  { kana: 'いのしし', romaji: 'inoshishi', meaning: 'wild boar' },
  { kana: 'くじら', romaji: 'kujira', meaning: 'whale' },
  { kana: 'いるか', romaji: 'iruka', meaning: 'dolphin' },
  { kana: 'ぺんぎん', romaji: 'pengin', meaning: 'penguin' },
  { kana: 'とり', romaji: 'tori', meaning: 'bird' },
  { kana: 'すずめ', romaji: 'suzume', meaning: 'sparrow' },
  { kana: 'からす', romaji: 'karasu', meaning: 'crow' },
  { kana: 'はと', romaji: 'hato', meaning: 'pigeon' },
  { kana: 'あひる', romaji: 'ahiru', meaning: 'duck' },
  { kana: 'つばめ', romaji: 'tsubame', meaning: 'swallow' },
  { kana: 'たか', romaji: 'taka', meaning: 'hawk' },
  { kana: 'わし', romaji: 'washi', meaning: 'eagle' },
  { kana: 'ふくろう', romaji: 'fukurou', meaning: 'owl' },
  { kana: 'こうもり', romaji: 'koumori', meaning: 'bat' },
  { kana: 'むら', romaji: 'mura', meaning: 'village' },
  { kana: 'まち', romaji: 'machi', meaning: 'town' },
  { kana: 'くに', romaji: 'kuni', meaning: 'country' },
  { kana: 'せかい', romaji: 'sekai', meaning: 'world' },
  { kana: 'ちきゅう', romaji: 'chikyuu', meaning: 'earth', youon: true },
  { kana: 'たいよう', romaji: 'taiyou', meaning: 'sun', youon: true },
  { kana: 'つき', romaji: 'tsuki', meaning: 'moon' },
  { kana: 'ほし', romaji: 'hoshi', meaning: 'star' },
  { kana: 'うちゅう', romaji: 'uchuu', meaning: 'space', youon: true },
  { kana: 'てんき', romaji: 'tenki', meaning: 'weather' },
  { kana: 'はれ', romaji: 'hare', meaning: 'sunny' },
  { kana: 'くもり', romaji: 'kumori', meaning: 'cloudy' },
  { kana: 'あめ', romaji: 'ame', meaning: 'rain' },
  { kana: 'ゆき', romaji: 'yuki', meaning: 'snow' },
  { kana: 'かみなり', romaji: 'kaminari', meaning: 'thunder' },
  { kana: 'たいふう', romaji: 'taifuu', meaning: 'typhoon' },
  { kana: 'じしん', romaji: 'jishin', meaning: 'earthquake' },
  { kana: 'つなみ', romaji: 'tsunami', meaning: 'tsunami' },
  { kana: 'かざん', romaji: 'kazan', meaning: 'volcano' },
  { kana: 'しぜん', romaji: 'shizen', meaning: 'nature' },
  { kana: 'やま', romaji: 'yama', meaning: 'mountain' },
  { kana: 'かわ', romaji: 'kawa', meaning: 'river' },
  { kana: 'うみ', romaji: 'umi', meaning: 'sea' },
  { kana: 'みずうみ', romaji: 'mizuumi', meaning: 'lake' },
  { kana: 'いけ', romaji: 'ike', meaning: 'pond' },
  { kana: 'もり', romaji: 'mori', meaning: 'forest' },
  { kana: 'はやし', romaji: 'hayashi', meaning: 'grove' },
  { kana: 'そうげん', romaji: 'sougen', meaning: 'grassland' },
  { kana: 'さばく', romaji: 'sabaku', meaning: 'desert' },
  { kana: 'しま', romaji: 'shima', meaning: 'island' },
  { kana: 'きせつ', romaji: 'kisetsu', meaning: 'season' },
  { kana: 'はる', romaji: 'haru', meaning: 'spring' },
  { kana: 'なつ', romaji: 'natsu', meaning: 'summer' },
  { kana: 'あき', romaji: 'aki', meaning: 'autumn' },
  { kana: 'ふゆ', romaji: 'fuyu', meaning: 'winter' },
  { kana: 'あさ', romaji: 'asa', meaning: 'morning' },
  { kana: 'ひる', romaji: 'hiru', meaning: 'noon / afternoon' },
  { kana: 'ゆうがた', romaji: 'yuugata', meaning: 'evening' },
  { kana: 'よる', romaji: 'yoru', meaning: 'night' },
  { kana: 'まよなか', romaji: 'mayonaka', meaning: 'midnight' },
  { kana: 'きょう', romaji: 'kyou', meaning: 'today', youon: true },
  { kana: 'あした', romaji: 'ashita', meaning: 'tomorrow' },
  { kana: 'きのう', romaji: 'kinou', meaning: 'yesterday' },
  { kana: 'こんしゅう', romaji: 'konshuu', meaning: 'this week', youon: true },
  { kana: 'らいしゅう', romaji: 'raishuu', meaning: 'next week', youon: true },
  { kana: 'せんしゅう', romaji: 'senshuu', meaning: 'last week', youon: true },
  { kana: 'こんげつ', romaji: 'kongetsu', meaning: 'this month' },
  { kana: 'らいげつ', romaji: 'raigetsu', meaning: 'next month' },
  { kana: 'せんげつ', romaji: 'sengetsu', meaning: 'last month' },
  { kana: 'ことし', romaji: 'kotoshi', meaning: 'this year' },
  { kana: 'らいねん', romaji: 'rainen', meaning: 'next year' },
  { kana: 'きょねん', romaji: 'kyonen', meaning: 'last year', youon: true },
  { kana: 'たんじょうび', romaji: 'tanjoubi', meaning: 'birthday' },
];

export const WORDS_KATAKANA = [
  // --- Original List ---
  { kana: 'アイスクリーム', romaji: 'aisukuriimu', meaning: 'ice cream' },
  { kana: 'アニメ', romaji: 'anime', meaning: 'anime' },
  { kana: 'アパート', romaji: 'apaato', meaning: 'apartment' },
  { kana: 'イベント', romaji: 'ibento', meaning: 'event' },
  { kana: 'インターネット', romaji: 'intaanetto', meaning: 'internet' },
  { kana: 'ウイルス', romaji: 'uirusu', meaning: 'virus' },
  { kana: 'エネルギー', romaji: 'enerugii', meaning: 'energy' },
  { kana: 'エレベーター', romaji: 'erebeetaa', meaning: 'elevator' },
  { kana: 'オレンジ', romaji: 'orenji', meaning: 'orange' },
  { kana: 'カメラ', romaji: 'kamera', meaning: 'camera' },
  { kana: 'ギター', romaji: 'gitaa', meaning: 'guitar' },
  { kana: 'コーヒー', romaji: 'koohii', meaning: 'coffee' },
  { kana: 'コンピューター', romaji: 'konpyuutaa', meaning: 'computer', youon: true },
  { kana: 'サッカー', romaji: 'sakkaa', meaning: 'soccer' },
  { kana: 'スーパー', romaji: 'suupaa', meaning: 'supermarket' },
  { kana: 'スマートフォン', romaji: 'sumaatofon', meaning: 'smartphone' },
  { kana: 'セーター', romaji: 'seetaa', meaning: 'sweater' },
  { kana: 'タクシー', romaji: 'takushii', meaning: 'taxi' },
  { kana: 'チョコレート', romaji: 'chokoreeto', meaning: 'chocolate' },
  { kana: 'テーブル', romaji: 'teeburu', meaning: 'table' },
  { kana: 'テレビ', romaji: 'terebi', meaning: 'TV' },
  { kana: 'ドア', romaji: 'doa', meaning: 'door' },
  { kana: 'トイレ', romaji: 'toire', meaning: 'toilet' },
  { kana: 'ニュース', romaji: 'nyuusu', meaning: 'news', youon: true },
  { kana: 'ノート', romaji: 'nooto', meaning: 'notebook' },
  { kana: 'パソコン', romaji: 'pasokon', meaning: 'personal computer' },
  { kana: 'バス', romaji: 'basu', meaning: 'bus' },
  { kana: 'ピアノ', romaji: 'piano', meaning: 'piano' },
  { kana: 'ビール', romaji: 'biiru', meaning: 'beer' },
  { kana: 'ファッション', romaji: 'fasshon', meaning: 'fashion', youon: true },
  { kana: 'フォーク', romaji: 'fooku', meaning: 'fork', youon: true },
  { kana: 'プール', romaji: 'puuru', meaning: 'swimming pool' },
  { kana: 'ベッド', romaji: 'beddo', meaning: 'bed' },
  { kana: 'ボール', romaji: 'booru', meaning: 'ball' },
  { kana: 'マクドナルド', romaji: 'makudonarudo', meaning: 'McDonald\'s' },
  { kana: 'メニュー', romaji: 'menyuu', meaning: 'menu', youon: true },
  { kana: 'ライター', romaji: 'raitaa', meaning: 'lighter' },
  { kana: 'レストラン', romaji: 'resutoran', meaning: 'restaurant' },
  { kana: 'ロボット', romaji: 'robotto', meaning: 'robot' },
  { kana: 'ワイン', romaji: 'wain', meaning: 'wine' },
  { kana: 'シャワー', romaji: 'shawaa', meaning: 'shower', youon: true },
  { kana: 'ジュース', romaji: 'juusu', meaning: 'juice', youon: true },
  { kana: 'チャンネル', romaji: 'channeru', meaning: 'TV channel', youon: true },
  { kana: 'キャラクター', romaji: 'kyarakutaa', meaning: 'character', youon: true },
  { kana: 'ショッピング', romaji: 'shoppingu', meaning: 'shopping', youon: true },
  { kana: 'チケット', romaji: 'chiketto', meaning: 'ticket' },

  // --- 300 New Katakana Words ---
  { kana: 'ペン', romaji: 'pen', meaning: 'pen' },
  { kana: 'コップ', romaji: 'koppu', meaning: 'cup' },
  { kana: 'ガラス', romaji: 'garasu', meaning: 'glass' },
  { kana: 'ナイフ', romaji: 'naifu', meaning: 'knife' },
  { kana: 'スプーン', romaji: 'supuun', meaning: 'spoon' },
  { kana: 'パン', romaji: 'pan', meaning: 'bread' },
  { kana: 'バター', romaji: 'bataa', meaning: 'butter' },
  { kana: 'サラダ', romaji: 'sarada', meaning: 'salad' },
  { kana: 'サンドイッチ', romaji: 'sandoitchi', meaning: 'sandwich' },
  { kana: 'ステーキ', romaji: 'suteeki', meaning: 'steak' },
  { kana: 'ハンバーグ', romaji: 'hanbaagu', meaning: 'hamburger steak' },
  { kana: 'カレー', romaji: 'karee', meaning: 'curry' },
  { kana: 'パスタ', romaji: 'pasuta', meaning: 'pasta' },
  { kana: 'ケーキ', romaji: 'keeki', meaning: 'cake' },
  { kana: 'ジャム', romaji: 'jamu', meaning: 'jam' },
  { kana: 'ミルク', romaji: 'miruku', meaning: 'milk' },
  { kana: 'ヨーグルト', romaji: 'yooguruto', meaning: 'yogurt' },
  { kana: 'チーズ', romaji: 'chiizu', meaning: 'cheese' },
  { kana: 'ソーセージ', romaji: 'sooseeji', meaning: 'sausage' },
  { kana: 'ハム', romaji: 'hamu', meaning: 'ham' },
  { kana: 'コーラ', romaji: 'koora', meaning: 'cola' },
  { kana: 'スープ', romaji: 'suupu', meaning: 'soup' },
  { kana: 'デザート', romaji: 'dezaato', meaning: 'dessert' },
  { kana: 'レモン', romaji: 'remon', meaning: 'lemon' },
  { kana: 'バナナ', romaji: 'banana', meaning: 'banana' },
  { kana: 'パイナップル', romaji: 'painappuru', meaning: 'pineapple' },
  { kana: 'メロン', romaji: 'meron', meaning: 'melon' },
  { kana: 'イチゴ', romaji: 'ichigo', meaning: 'strawberry' },
  { kana: 'トマト', romaji: 'tomato', meaning: 'tomato' },
  { kana: 'ポテト', romaji: 'poteto', meaning: 'potato' },
  { kana: 'キャベツ', romaji: 'kyabetsu', meaning: 'cabbage' },
  { kana: 'レタス', romaji: 'retasu', meaning: 'lettuce' },
  { kana: 'シャツ', romaji: 'shatsu', meaning: 'shirt', youon: true },
  { kana: 'Ｔシャツ', romaji: 'tiishatsu', meaning: 'T-shirt', youon: true },
  { kana: 'ズボン', romaji: 'zubon', meaning: 'pants' },
  { kana: 'スカート', romaji: 'sukaato', meaning: 'skirt' },
  { kana: 'ネクタイ', romaji: 'nekutai', meaning: 'necktie' },
  { kana: 'コート', romaji: 'kooto', meaning: 'coat' },
  { kana: 'ジャケット', romaji: 'jaketto', meaning: 'jacket' },
  { kana: 'ドレス', romaji: 'doresu', meaning: 'dress' },
  { kana: 'ワンピース', romaji: 'wanpiisu', meaning: 'one-piece dress' },
  { kana: 'スーツ', romaji: 'suutsu', meaning: 'suit' },
  { kana: 'ジーンズ', romaji: 'jiinzu', meaning: 'jeans' },
  { kana: 'ベルト', romaji: 'beruto', meaning: 'belt' },
  { kana: 'スニーカー', romaji: 'suniikaa', meaning: 'sneakers' },
  { kana: 'サンダル', romaji: 'sandaru', meaning: 'sandals' },
  { kana: 'ブーツ', romaji: 'buutsu', meaning: 'boots' },
  { kana: 'スリッパ', romaji: 'surippa', meaning: 'slippers' },
  { kana: 'バッグ', romaji: 'baggu', meaning: 'bag' },
  { kana: 'ポケット', romaji: 'poketto', meaning: 'pocket' },
  { kana: 'ボタン', romaji: 'botan', meaning: 'button' },
  { kana: 'ハンカチ', romaji: 'hankachi', meaning: 'handkerchief' },
  { kana: 'マスク', romaji: 'masuku', meaning: 'mask' },
  { kana: 'タオル', romaji: 'taoru', meaning: 'towel' },
  { kana: 'ブラシ', romaji: 'burashi', meaning: 'brush' },
  { kana: 'ドライヤー', romaji: 'doraiyaa', meaning: 'hair dryer', youon: true },
  { kana: 'シャンプー', romaji: 'shanpuu', meaning: 'shampoo' },
  { kana: 'リンス', romaji: 'rinsu', meaning: 'conditioner' },
  { kana: 'ソープ', romaji: 'soopu', meaning: 'soap' },
  { kana: 'ベッド', romaji: 'beddo', meaning: 'bed' },
  { kana: 'カーテン', romaji: 'kaaten', meaning: 'curtain' },
  { kana: 'ランプ', romaji: 'ranpu', meaning: 'lamp' },
  { kana: 'テレビ', romaji: 'terebi', meaning: 'TV' },
  { kana: 'ラジオ', romaji: 'rajio', meaning: 'radio' },
  { kana: 'ビデオ', romaji: 'bideo', meaning: 'video' },
  { kana: 'カメラ', romaji: 'kamera', meaning: 'camera' },
  { kana: 'デジタル', romaji: 'dejitaru', meaning: 'digital' },
  { kana: 'スマホ', romaji: 'sumaho', meaning: 'smartphone' },
  { kana: 'アプリ', romaji: 'apuri', meaning: 'app' },
  { kana: 'マウス', romaji: 'mausu', meaning: 'mouse' },
  { kana: 'キーボード', romaji: 'kiiboodo', meaning: 'keyboard' },
  { kana: 'モニター', romaji: 'monitaa', meaning: 'monitor' },
  { kana: 'プリント', romaji: 'purinto', meaning: 'print / handout' },
  { kana: 'コピー', romaji: 'kopii', meaning: 'copy' },
  { kana: 'ファクス', romaji: 'fakusu', meaning: 'fax' },
  { kana: 'ファイル', romaji: 'fairu', meaning: 'file' },
  { kana: 'フォルダ', romaji: 'foruda', meaning: 'folder' },
  { kana: 'ディスク', romaji: 'disuku', meaning: 'disk' },
  { kana: 'メモリ', romaji: 'memori', meaning: 'memory' },
  { kana: 'ハード', romaji: 'haado', meaning: 'hard' },
  { kana: 'ソフト', romaji: 'sofuto', meaning: 'soft' },
  { kana: 'ゲーム', romaji: 'geemu', meaning: 'game' },
  { kana: 'カード', romaji: 'kaado', meaning: 'card' },
  { kana: 'カレンダー', romaji: 'karendaa', meaning: 'calendar' },
  { kana: 'カタログ', romaji: 'katarogu', meaning: 'catalog' },
  { kana: 'パンフレット', romaji: 'panfuretto', meaning: 'pamphlet' },
  { kana: 'テキスト', romaji: 'tekisuto', meaning: 'textbook' },
  { kana: 'ノート', romaji: 'nooto', meaning: 'notebook' },
  { kana: 'メモ', romaji: 'memo', meaning: 'memo' },
  { kana: 'サイン', romaji: 'sain', meaning: 'signature' },
  { kana: 'マーク', romaji: 'maaku', meaning: 'mark' },
  { kana: 'ラベル', romaji: 'raberu', meaning: 'label' },
  { kana: 'テープ', romaji: 'teepu', meaning: 'tape' },
  { kana: 'インク', romaji: 'inku', meaning: 'ink' },
  { kana: 'ゴム', romaji: 'gomu', meaning: 'rubber / eraser' },
  { kana: 'ペンチ', romaji: 'penchi', meaning: 'pliers' },
  { kana: 'ハンマー', romaji: 'hanmaa', meaning: 'hammer' },
  { kana: 'ドライバー', romaji: 'doraibaa', meaning: 'screwdriver' },
  { kana: 'タイヤ', romaji: 'taiya', meaning: 'tire' },
  { kana: 'エンジン', romaji: 'enjin', meaning: 'engine' },
  { kana: 'ガソリン', romaji: 'gasorin', meaning: 'gasoline' },
  { kana: 'ハンドル', romaji: 'handoru', meaning: 'steering wheel / handle' },
  { kana: 'ブレーキ', romaji: 'bureeki', meaning: 'brake' },
  { kana: 'ライト', romaji: 'raito', meaning: 'light' },
  { kana: 'バス', romaji: 'basu', meaning: 'bus' },
  { kana: 'タクシー', romaji: 'takushii', meaning: 'taxi' },
  { kana: 'トラック', romaji: 'torakku', meaning: 'truck' },
  { kana: 'バイク', romaji: 'baiku', meaning: 'motorcycle' },
  { kana: 'ボート', romaji: 'booto', meaning: 'boat' },
  { kana: 'ヨット', romaji: 'yotto', meaning: 'yacht' },
  { kana: 'ジェット', romaji: 'jetto', meaning: 'jet' },
  { kana: 'ヘリコプター', romaji: 'herikoputaa', meaning: 'helicopter' },
  { kana: 'ロケット', romaji: 'roketto', meaning: 'rocket' },
  { kana: 'ビル', romaji: 'biru', meaning: 'building' },
  { kana: 'マンション', romaji: 'manshon', meaning: 'apartment' },
  { kana: 'ホテル', romaji: 'hoteru', meaning: 'hotel' },
  { kana: 'デパート', romaji: 'depaato', meaning: 'department store' },
  { kana: 'コンビニ', romaji: 'konbini', meaning: 'convenience store' },
  { kana: 'スーパー', romaji: 'suupaa', meaning: 'supermarket' },
  { kana: 'レストラン', romaji: 'resutoran', meaning: 'restaurant' },
  { kana: 'カフェ', romaji: 'kafe', meaning: 'cafe' },
  { kana: 'バー', romaji: 'baa', meaning: 'bar' },
  { kana: 'ショップ', romaji: 'shoppu', meaning: 'shop' },
  { kana: 'オフィス', romaji: 'ofisu', meaning: 'office' },
  { kana: 'スタジオ', romaji: 'sutajio', meaning: 'studio' },
  { kana: 'ジム', romaji: 'jimu', meaning: 'gym' },
  { kana: 'シアター', romaji: 'shiataa', meaning: 'theater' },
  { kana: 'ホール', romaji: 'hooru', meaning: 'hall' },
  { kana: 'ステージ', romaji: 'steeji', meaning: 'stage' },
  { kana: 'キャンプ', romaji: 'kyanpu', meaning: 'camp' },
  { kana: 'ピクニック', romaji: 'pikunikku', meaning: 'picnic' },
  { kana: 'スポーツ', romaji: 'supootsu', meaning: 'sports' },
  { kana: 'テニス', romaji: 'tenisu', meaning: 'tennis' },
  { kana: 'ゴルフ', romaji: 'gorufu', meaning: 'golf' },
  { kana: 'スキー', romaji: 'sukii', meaning: 'skiing' },
  { kana: 'スケート', romaji: 'sukeeto', meaning: 'skating' },
  { kana: 'サーフィン', romaji: 'saafin', meaning: 'surfing' },
  { kana: 'マラソン', romaji: 'marason', meaning: 'marathon' },
  { kana: 'ジョギング', romaji: 'jogingu', meaning: 'jogging' },
  { kana: 'バレー', romaji: 'baree', meaning: 'volleyball' },
  { kana: 'バスケ', romaji: 'basuke', meaning: 'basketball' },
  { kana: 'ダンス', romaji: 'dansu', meaning: 'dance' },
  { kana: 'バレエ', romaji: 'baree', meaning: 'ballet' },
  { kana: 'ピアノ', romaji: 'piano', meaning: 'piano' },
  { kana: 'バイオリン', romaji: 'baiorin', meaning: 'violin' },
  { kana: 'ドラム', romaji: 'doramu', meaning: 'drum' },
  { kana: 'ライブ', romaji: 'raibu', meaning: 'live show' },
  { kana: 'コンサート', romaji: 'konsaato', meaning: 'concert' },
  { kana: 'ジャズ', romaji: 'jazu', meaning: 'jazz' },
  { kana: 'ロック', romaji: 'rokku', meaning: 'rock' },
  { kana: 'ポップス', romaji: 'poppusu', meaning: 'pop music' },
  { kana: 'クラシック', romaji: 'kurashikku', meaning: 'classical music' },
  { kana: 'メロディー', romaji: 'merodii', meaning: 'melody' },
  { kana: 'リズム', romaji: 'rizumu', meaning: 'rhythm' },
  { kana: 'アート', romaji: 'aato', meaning: 'art' },
  { kana: 'デザイン', romaji: 'dezain', meaning: 'design' },
  { kana: 'モデル', romaji: 'moderu', meaning: 'model' },
  { kana: 'スタイル', romaji: 'sutairu', meaning: 'style' },
  { kana: 'イメージ', romaji: 'imeeji', meaning: 'image' },
  { kana: 'アイデア', romaji: 'aidea', meaning: 'idea' },
  { kana: 'ヒント', romaji: 'hinto', meaning: 'hint' },
  { kana: 'ミス', romaji: 'misu', meaning: 'mistake' },
  { kana: 'トラブル', romaji: 'toraburu', meaning: 'trouble' },
  { kana: 'ショック', romaji: 'shokku', meaning: 'shock' },
  { kana: 'ストレス', romaji: 'sutoresu', meaning: 'stress' },
  { kana: 'リラックス', romaji: 'rirakkusu', meaning: 'relax' },
  { kana: 'ハッピー', romaji: 'happii', meaning: 'happy' },
  { kana: 'ラッキー', romaji: 'rakkii', meaning: 'lucky' },
  { kana: 'チャンス', romaji: 'chansu', meaning: 'chance', youon: true },
  { kana: 'ボーナス', romaji: 'boonasu', meaning: 'bonus' },
  { kana: 'プレゼント', romaji: 'purezento', meaning: 'present' },
  { kana: 'ギフト', romaji: 'gifuto', meaning: 'gift' },
  { kana: 'サービス', romaji: 'saabisu', meaning: 'service' },
  { kana: 'ルール', romaji: 'ruuru', meaning: 'rule' },
  { kana: 'マナー', romaji: 'manaa', meaning: 'manners' },
  { kana: 'チーム', romaji: 'chiimu', meaning: 'team' },
  { kana: 'メンバー', romaji: 'menbaa', meaning: 'member' },
  { kana: 'リーダー', romaji: 'riidaa', meaning: 'leader' },
  { kana: 'プロ', romaji: 'puro', meaning: 'professional' },
  { kana: 'アマ', romaji: 'ama', meaning: 'amateur' },
  { kana: 'レベル', romaji: 'reberu', meaning: 'level' },
  { kana: 'コース', romaji: 'koosu', meaning: 'course' },
  { kana: 'クラス', romaji: 'kurasu', meaning: 'class' },
  { kana: 'ページ', romaji: 'peeji', meaning: 'page' },
  { kana: 'タイトル', romaji: 'taitoru', meaning: 'title' },
  { kana: 'メッセージ', romaji: 'messeegi', meaning: 'message' },
  { kana: 'ニュース', romaji: 'nyuusu', meaning: 'news', youon: true },
  { kana: 'インタビュー', romaji: 'intabyuu', meaning: 'interview', youon: true },
  { kana: 'レポート', romaji: 'repooto', meaning: 'report' },
  { kana: 'データ', romaji: 'deeta', meaning: 'data' },
  { kana: 'システム', romaji: 'shisutemu', meaning: 'system' },
  { kana: 'プログラム', romaji: 'puroguramu', meaning: 'program' },
  { kana: 'ネット', romaji: 'netto', meaning: 'net' },
  { kana: 'ウェブ', romaji: 'webu', meaning: 'web' },
  { kana: 'メール', romaji: 'meeru', meaning: 'email' },
  { kana: 'リンク', romaji: 'rinku', meaning: 'link' },
  { kana: 'クリック', romaji: 'kurikku', meaning: 'click' },
  { kana: 'ログイン', romaji: 'roguin', meaning: 'login' },
  { kana: 'パスワード', romaji: 'pasuwaado', meaning: 'password' },
  { kana: 'アップデート', romaji: 'appudeeto', meaning: 'update' },
  { kana: 'チェック', romaji: 'chekku', meaning: 'check', youon: true },
  { kana: 'スタート', romaji: 'sutaato', meaning: 'start' },
  { kana: 'ゴール', romaji: 'gooru', meaning: 'goal' },
  { kana: 'ストップ', romaji: 'stoppu', meaning: 'stop' },
  { kana: 'オープン', romaji: 'oopun', meaning: 'open' },
  { kana: 'クローズ', romaji: 'kuroozu', meaning: 'close' },
  { kana: 'センター', romaji: 'sentaa', meaning: 'center' },
  { kana: 'フロント', romaji: 'furonto', meaning: 'front' },
  { kana: 'バック', romaji: 'bakku', meaning: 'back' },
  { kana: 'サイド', romaji: 'saido', meaning: 'side' },
  { kana: 'トップ', romaji: 'toppu', meaning: 'top' },
  { kana: 'ラスト', romaji: 'rasuto', meaning: 'last' },
  { kana: 'プラス', romaji: 'purasu', meaning: 'plus' },
  { kana: 'マイナス', romaji: 'mainasu', meaning: 'minus' },
  { kana: 'ゼロ', romaji: 'zero', meaning: 'zero' },
  { kana: 'ナンバー', romaji: 'nanbaa', meaning: 'number' },
  { kana: 'サイズ', romaji: 'saizu', meaning: 'size' },
  { kana: 'カラー', romaji: 'karaa', meaning: 'color' },
  { kana: 'スピード', romaji: 'supiido', meaning: 'speed' },
  { kana: 'コスト', romaji: 'kosuto', meaning: 'cost' },
  { kana: 'パワー', romaji: 'pawaa', meaning: 'power' },
  { kana: 'ポイント', romaji: 'pointo', meaning: 'point' },
  { kana: 'ウェイト', romaji: 'weito', meaning: 'weight' },
  { kana: 'バランス', romaji: 'baransu', meaning: 'balance' },
  { kana: 'エネルギー', romaji: 'enerugii', meaning: 'energy' },
  { kana: 'センス', romaji: 'sensu', meaning: 'sense' },
  { kana: 'ユーモア', romaji: 'yuumoa', meaning: 'humor', youon: true },
  { kana: 'ムード', romaji: 'muudo', meaning: 'mood' },
  { kana: 'ロマン', romaji: 'roman', meaning: 'romance' },
  { kana: 'ドラマ', romaji: 'dorama', meaning: 'drama' },
  { kana: 'アニメ', romaji: 'anime', meaning: 'animation' },
  { kana: 'ファン', romaji: 'fan', meaning: 'fan' },
  { kana: 'スター', romaji: 'sutaa', meaning: 'star' },
  { kana: 'アイドル', romaji: 'aidoru', meaning: 'idol' },
  { kana: 'ゲスト', romaji: 'gesuto', meaning: 'guest' },
  { kana: 'ホスト', romaji: 'hosuto', meaning: 'host' },
  { kana: 'プロデューサー', romaji: 'purodyuusaa', meaning: 'producer', youon: true },
  { kana: 'ディレクター', romaji: 'direkutaa', meaning: 'director' },
  { kana: 'マネージャー', romaji: 'maneejaa', meaning: 'manager' },
  { kana: 'スタッフ', romaji: 'sutaffu', meaning: 'staff' },
  { kana: 'ガイド', romaji: 'gaido', meaning: 'guide' },
  { kana: 'ドライバー', romaji: 'doraibaa', meaning: 'driver' },
  { kana: 'パイロット', romaji: 'pairotto', meaning: 'pilot' },
  { kana: 'ドクター', romaji: 'dokutaa', meaning: 'doctor' },
  { kana: 'ナース', romaji: 'naasu', meaning: 'nurse' },
  { kana: 'ボランティア', romaji: 'borantia', meaning: 'volunteer', youon: true },
  { kana: 'グループ', romaji: 'guruupu', meaning: 'group' },
  { kana: 'サークル', romaji: 'saakuru', meaning: 'circle / club' },
  { kana: 'パーティー', romaji: 'paatii', meaning: 'party' },
  { kana: 'ピザ', romaji: 'piza', meaning: 'pizza' },
  { kana: 'コーラ', romaji: 'koora', meaning: 'cola' },
  { kana: 'ウイスキー', romaji: 'uisukii', meaning: 'whiskey' },
  { kana: 'ブランデー', romaji: 'burandee', meaning: 'brandy' },
  { kana: 'カクテル', romaji: 'kakuteru', meaning: 'cocktail' },
  { kana: 'シャンパン', romaji: 'shanpan', meaning: 'champagne' },
  { kana: 'ワイン', romaji: 'wain', meaning: 'wine' },
  { kana: 'ガム', romaji: 'gamu', meaning: 'chewing gum' },
  { kana: 'チョコ', romaji: 'choko', meaning: 'chocolate' },
  { kana: 'クッキー', romaji: 'kukkii', meaning: 'cookie' },
  { kana: 'ドーナツ', romaji: 'doonatsu', meaning: 'donut' },
  { kana: 'ゼリー', romaji: 'zerii', meaning: 'jelly' },
  { kana: 'アイス', romaji: 'aisu', meaning: 'ice / ice cream' },
  { kana: 'ココア', romaji: 'kokoa', meaning: 'cocoa' },
  { kana: 'ミルク', romaji: 'miruku', meaning: 'milk' },
  { kana: 'アメリカ', romaji: 'amerika', meaning: 'USA' },
  { kana: 'イギリス', romaji: 'igirisu', meaning: 'UK' },
  { kana: 'フランス', romaji: 'furansu', meaning: 'France' },
  { kana: 'ドイツ', romaji: 'doitsu', meaning: 'Germany' },
  { kana: 'イタリア', romaji: 'itaria', meaning: 'Italy' },
  { kana: 'スペイン', romaji: 'supein', meaning: 'Spain' },
  { kana: 'ロシア', romaji: 'roshia', meaning: 'Russia' },
  { kana: 'カナダ', romaji: 'kanada', meaning: 'Canada' },
  { kana: 'ブラジル', romaji: 'burajiru', meaning: 'Brazil' },
  { kana: 'アジア', romaji: 'ajia', meaning: 'Asia' },
  { kana: 'アフリカ', romaji: 'afurika', meaning: 'Africa' },
  { kana: 'ヨーロッパ', romaji: 'yooroppa', meaning: 'Europe' },
  { kana: 'ダイヤモンド', romaji: 'daiyamondo', meaning: 'diamond', youon: true },
  { kana: 'ルビー', romaji: 'rubii', meaning: 'ruby' },
  { kana: 'サファイア', romaji: 'safaia', meaning: 'sapphire', youon: true },
  { kana: 'ゴールド', romaji: 'goorudo', meaning: 'gold' },
  { kana: 'シルバー', romaji: 'shirubaa', meaning: 'silver' },
  { kana: 'プラチナ', romaji: 'purachina', meaning: 'platinum' },
  { kana: 'プラスチック', romaji: 'purasuchikku', meaning: 'plastic' },
  { kana: 'ガラス', romaji: 'garasu', meaning: 'glass' },
  { kana: 'ビニール', romaji: 'biniiru', meaning: 'vinyl' },
  { kana: 'ゴム', romaji: 'gomu', meaning: 'rubber' },
  { kana: 'ペンキ', romaji: 'penki', meaning: 'paint' },
  { kana: 'オイル', romaji: 'oiru', meaning: 'oil' },
  { kana: 'ガソリン', romaji: 'gasorin', meaning: 'gasoline' },
  { kana: 'タバコ', romaji: 'tabako', meaning: 'tobacco / cigarette' },
  { kana: 'マッチ', romaji: 'matchi', meaning: 'match' },
  { kana: 'キャンドル', romaji: 'kyandoru', meaning: 'candle' },
  { kana: 'クリスマス', romaji: 'kurisumasu', meaning: 'Christmas' },
  { kana: 'ハロウィン', romaji: 'harowin', meaning: 'Halloween' },
  { kana: 'バレンタイン', romaji: 'barentain', meaning: 'Valentine' },
  { kana: 'プレゼント', romaji: 'purezento', meaning: 'present' },
  { kana: 'ケーキ', romaji: 'keeki', meaning: 'cake' },
  { kana: 'シャンパン', romaji: 'shanpan', meaning: 'champagne' },
];
